from typing import Protocol


class ProductAdminContract(Protocol):
    async def health_check(self) -> dict:
        ...

    async def get_organizations(self) -> list[dict]:
        ...

    async def get_organization_detail(self, product_organization_id: str) -> object:
        ...

    async def get_billing(self, product_organization_id: str) -> dict:
        ...

    async def update_billing(self, product_organization_id: str, payload: dict, idempotency_key: str) -> dict:
        ...

    async def add_credits(self, product_organization_id: str, payload: dict, idempotency_key: str) -> dict:
        ...

    async def deduct_credits(self, product_organization_id: str, payload: dict, idempotency_key: str) -> dict:
        ...

    async def record_manual_payment(self, product_organization_id: str, payload: dict, idempotency_key: str) -> dict:
        ...

    async def get_token_usage(self, product_organization_id: str) -> dict:
        ...

    async def get_revenue(self) -> dict:
        ...

    async def get_plans(self) -> list[dict]:
        ...

    async def get_models(self) -> list[dict]:
        ...

    async def create_impersonation_token(self, product_organization_id: str, idempotency_key: str) -> dict:
        ...

    async def get_sync_status(self) -> dict:
        ...
